name: IM
host: 0.0.0.0
port: 8002
endpoints: 
  - path: /shutdown
    method: GET
    description: Shutdown the channel
    capabilities: ['This is a channel module, the major functionality is to shutdown the channel.']
    input: {}
    output: {"result": "The result of the shutdown"}