available_llms:
- qwen25_1.5B_q8
- deepseek_r1_qwen_1.5B_q4_k_m
- qwq_32B_q4_k_m
- deepseek_r1_qwen_14B_q5_k_m
embedding_llm: embedding_text_model
silent: false
use_memory: true
embeddingTokensLen: 8192
endpoints:
- capabilities: []
  description: Register a helper with metadata, which can be used for core to select
    the most proper helper to work.
  input: {}
  method: POST
  output: {}
  path: /register_helper
- capabilities: []
  description: Handle a request from channel or helper.
  input: {}
  method: POST
  output: {}
  path: /process
host: 0.0.0.0
main_llm: deepseek_r1_qwen_14B_q5_k_m
mode: dev
model_path: ../models/
name: core
port: 9000
vectorDB:
  Chroma:
    anonymized_telemetry: false
    api: chromadb.api.fastapi.FastAPI
    host: 0.0.0.0
    is_persistent: true
    port: 5000
