name: core
host: 0.0.0.0
port: 9000
mode: dev
model_path: ../models/
main_llm: deepseek_r1_q4_k_m
#qwen2_7b_instruct_q4_k_m
memory_llm: llama_3_8B_q5_k_m_functionCall
embedding_llm: llama_3_8B_q5_k_m
vectorDB:
  Chroma:
    host: 0.0.0.0
    port: 5000
    api: chromadb.api.fastapi.FastAPI
    path: ../data
    persist_path: ../database
    is_persistent: true
    anonymized_telemetry: false
endpoints:
- path: /register_helper
  method: POST
  description: Register a helper with metadata, which can be used for core to
    select the most proper helper to work.
  capabilities: []
  input: {}
  output: {}
- path: /process
  method: POST
  description: Handle a request from channel or helper.
  capabilities: []
  input: {}
  output: {}
